### ISSUE TITLE
로그인 상태에서 페이지 새로고침시 failed to get cookies 에러 발생 

### ISSUE THREAD

**Issue by EUNSUN23** [oneMonthProject/Front#128]
## 버그 현상 
로그인 상태에서 어느 페이지에 있든지 새로고침하면 아래와 같은 에러가 발생합니다. 

![image](https://github.com/oneMonthProject/Front/assets/60612115/f307ed69-0a06-47c5-88ae-98fbd7c07f2e)

만약에 에러 해결이 어려우면 로그아웃 상태로 바꾼뒤 메인페이지로 리다이렉팅 해둬야 할 것 같아요. 

<br/>

## 스크린샷 (선택) 
> 문제를 설명하는데 도움이 되는 스크린샷을 추가합니다

**Comment by moa1128** [comment]
이거 처음 백엔드와 연결했을 때도 일어났던 문제였는데요 그 때도 해결이 되지 않아 화면 공유하면서 일단 나중에 처리하자고 했던 부분인데
혹시 마지막에 말씀해주신 해결방안은 좀 더 자세히 알 수 있을까요?

**Comment by EUNSUN23** [comment]
> 이거 처음 백엔드와 연결했을 때도 일어났던 문제였는데요 그 때도 해결이 되지 않아 화면 공유하면서 일단 나중에 처리하자고 했던 부분인데 혹시 마지막에 말씀해주신 해결방안은 좀 더 자세히 알 수 있을까요?

쿠키에 들어있는 토큰값, 로컬스토리지의 사용자정보 지우고 (로그아웃된 상태로 변경) 메인 페이지로 리다이렉팅 하면 어떨까요?

**Comment by moa1128** [comment]
새로고침을 눌렀을 때 처음에는 authApi 에서 cookie 에 있는 값을 가져오지 못해서 나는 오류라 
로그아웃과 동일한 프로세스 적용하는게 무슨 의미가 있는 지 모르겠어요..

**Comment by EUNSUN23** [comment]
> Member



> 새로고침을 눌렀을 때 처음에는 authApi 에서 cookie 에 있는 값을 가져오지 못해서 나는 오류라 로그아웃과 동일한 프로세스 적용하는게 무슨 의미가 있는 지 모르겠어요..

음 제가 하고싶었던 말은 쿠키값 가져오는것에 실패하면, 지금은 그냥 에러만 던지는데 그 에러던지는 부분에서 그냥 리프레쉬토큰, 유저아이디 등등 지우고 다시 로그인 할 수 있는 상태로 만들면 어떨까 하는 얘기였어요.
