### ISSUE TITLE
프로젝트 탈퇴 관련 API 요청 데이터 문의

### ISSUE THREAD

**Issue by songhyeonpk** [oneMonthProject/Front#137]
**1. 프로젝트 탈퇴 요청 API**<br>
   - API 엔드포인트:<br> `POST : /api/projectmember/{projectMemberId}/withdrawl` 
   - 문의:<br>프론트단에서 'project_member_id' 값을 요청할 수 있는지 문의드립니다. <br>만약 'project_member_id' 값을 보내기 어렵다면 엔드포인트를<br> `POST : /api/project/{projectId}/withdraw`로 수정하고 'project_id'와 요청한 회원의 'user_id' 값으로 로직을 처리할 수 있을 것 같습니다.<br><br><br>

**2. 프로젝트 탈퇴 컨펌 API**
   - API 엔드포인트:<br> `POST : /api/projectmember/{projectMemberId}/withdrawl/confirm`
   - 문의:<br> 'project_member_id' 혹은 탈퇴 알림의 'alert_id' 두 값중 어떤 값을 요청할 수 있는지 문의드립니다.<br>또한, 해당 API는 수락 혹은 거절 값을 함께 요청받아야 하므로 RequestBody를 통해 'project_member_id' 혹은 'alert_id' 둘 중 하나의 값과 boolean 타입의 수락/거절 값을 요청받아야 할 것 같습니다.

**Comment by EUNSUN23** [comment]
1. 프로젝트 탈퇴 요청 API
-> project_member_id 보내드릴 수 있을 것 같아요. 

2. 프로젝트 탈퇴 컨펌 API 
-> 이건 alert_id 값, boolean 타입의 수락/거절값 드릴 수 있을 것 같아요,

**Comment by songhyeonpk** [comment]
넵 수정하겠습니다
