### ISSUE TITLE
협조 요청 : 테스트 상세 페이지 조회

### ISSUE THREAD

**Issue by jkang1201** [oneMonthProject/Front#83]
요청사항:

프로젝트 메인 페이지의 동작 방식을 확인해보고 싶습니다.

이유:

현재 Figma로는 판단하기 애매한 부분이 있으며,

Figma를 봤을 땐 프로젝트 조회 시 딱 한 번만 매니저 권한 확인 하면 될듯함

![캡처](https://github.com/oneMonthProject/Front/assets/148705540/ab9c0379-039e-4e38-8094-1d6cfb8320ea)

문의:

업무를 추가할 때, 업무에 마일스톤을 넣어주는 값이 있어야 되는 건 아닌지 문의드립니다.

아니면 마일스톤 - 업무의 상하관계는 어떤 식으로 정립이 되나요?

![캡처2](https://github.com/oneMonthProject/Front/assets/148705540/21ffe11b-d8d5-4de7-ad00-0bf66687f47f)

(업무와 마일스톤 연결을 어떻게 하는지 애매, 프로젝트 페이지 작동 방식을 봐야 명확해질듯 함)

**Comment by moa1128** [comment]
은선님이 정확한 답변을 주시겠지만 제가 아는 선에서 말씀드리면
UI 적으로 마일스톤을 선택해서 클릭하면 하단에 해당 마일스톤에 속하는 업무들이 보여지고 그 상태에서 업무 추가 시 해당 마일스톤의 업무로 추가됩니다.
소면님 말씀대로 업무 추가할 때 프로젝트 id, 마일스톤 id 도 넘어가야 할 것 같습니다.

**Comment by jkang1201** [comment]
@moa1128 그러면 프로젝트 처음 들어갈 때 마일스톤 선택 안 한 상태에서는 업무들이 안 보이는 건가요? "내프로젝트" 들어가면 loading...만 나와서 파악이 잘 안 됩니다

**Comment by moa1128** [comment]
@jkang1201 
마일스톤 선택 안한 상태에서는 안보이거나 첫번째 항목을 자동 선택하고 해당 마일스톤에 속하는 업무들이 보일 것 같은데 이 부분은 은선님에게 다시 확인하시는게 좋을 것 같습니다.
지금 배포된 환경에서는 Loading 만 표시될 것 같아요.. 개발 환경에서는 테스트 api 가 연결이 되어서 테스트 값들이 보입니다.

**Comment by EUNSUN23** [comment]
@jkang1201 

1. 프로젝트 상세 페이지 진입시 사용자의 프로젝트 권한 조회는 최초 1회면 될것같습니다. 
2. 프로젝트 상세 최초 진입하면 먼저 마일스톤 목록을 조회하고, status 값이 진행중이고 startDate가 가장 빠른 마일스톤을 선택해서 해당 마일스톤의 업무 목록 조회하려고 합니다. 그 상태에서 업무를 추가/삭제/수정할시 해당 마일스톤의 id를 요청값에 넣으면 될 것 같습니다.

**Comment by jkang1201** [comment]
@EUNSUN23 혹시 이 화면 연결해보셨나요? 연결해보셨다면 url 정보 부탁드려도 될까요? 노션에 있는 거랑은 조금 다른 거 같아서요
